
package com.seeburger.research.policyengine.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-17T15:01:13.915+02:00
 * Generated source version: 2.7.4
 * 
 */
public final class IAccessManagement_IAccessManagementPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.policyengine.research.seeburger.com/", "IAccessManagementService");

    private IAccessManagement_IAccessManagementPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IAccessManagementService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IAccessManagementService ss = new IAccessManagementService(wsdlURL, SERVICE_NAME);
        IAccessManagement port = ss.getIAccessManagementPort();  
        
        {
        System.out.println("Invoking requestKeys...");
        byte[] _requestKeys_authToken = new byte[0];
        byte[] _requestKeys_requestId = new byte[0];
        com.seeburger.research.policyengine.ws.ResourceCoordinates _requestKeys_resourceCoordinates = null;
        try {
            port.requestKeys(_requestKeys_authToken, _requestKeys_requestId, _requestKeys_resourceCoordinates);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking storeActorAddress...");
        byte[] _storeActorAddress_encAuthToken = new byte[0];
        byte[] _storeActorAddress_encActorAddress = new byte[0];
        port.storeActorAddress(_storeActorAddress_encAuthToken, _storeActorAddress_encActorAddress);


        }

        System.exit(0);
    }

}
