package com.seeburger.research.securityframework.layers.keymanagement.sharing.requestor;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-17T15:01:15.074+02:00
 * Generated source version: 2.7.4
 * 
 */
@WebService(targetNamespace = "http://requestor.sharing.keymanagement.layers.securityframework.research.seeburger.com/", name = "IKeyRequestor")
@XmlSeeAlso({ObjectFactory.class})
public interface IKeyRequestor {

    @RequestWrapper(localName = "storeKeyPackage", targetNamespace = "http://requestor.sharing.keymanagement.layers.securityframework.research.seeburger.com/", className = "com.seeburger.research.securityframework.layers.keymanagement.sharing.requestor.StoreKeyPackage")
    @WebMethod
    @ResponseWrapper(localName = "storeKeyPackageResponse", targetNamespace = "http://requestor.sharing.keymanagement.layers.securityframework.research.seeburger.com/", className = "com.seeburger.research.securityframework.layers.keymanagement.sharing.requestor.StoreKeyPackageResponse")
    public void storeKeyPackage(
        @WebParam(name = "arg0", targetNamespace = "")
        com.seeburger.research.securityframework.layers.keymanagement.sharing.requestor.KeySharingPackage arg0
    );
}
