
package com.seeburger.research.securityframework.layers.keymanagement.sharing.requestor;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-17T15:01:15.063+02:00
 * Generated source version: 2.7.4
 * 
 */
public final class IKeyRequestor_IKeyRequestorPort_Client {

    private static final QName SERVICE_NAME = new QName("http://requestor.sharing.keymanagement.layers.securityframework.research.seeburger.com/", "IKeyRequestorService");

    private IKeyRequestor_IKeyRequestorPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IKeyRequestorService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IKeyRequestorService ss = new IKeyRequestorService(wsdlURL, SERVICE_NAME);
        IKeyRequestor port = ss.getIKeyRequestorPort();  
        
        {
        System.out.println("Invoking storeKeyPackage...");
        com.seeburger.research.securityframework.layers.keymanagement.sharing.requestor.KeySharingPackage _storeKeyPackage_arg0 = null;
        port.storeKeyPackage(_storeKeyPackage_arg0);


        }

        System.exit(0);
    }

}
