package com.seeburger.research.securityframework.layers.keymanagement.sharing.requestor;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2013-05-17T15:01:15.081+02:00
 * Generated source version: 2.7.4
 * 
 */
@WebServiceClient(name = "IKeyRequestorService", 
                  wsdlLocation = "file:/E:/IMSE/4.Thesis/Projects/ThesisProject/securityframework/../keyrequesteriface/src/main/resources/wsdl/KeyRequestorWS.wsdl",
                  targetNamespace = "http://requestor.sharing.keymanagement.layers.securityframework.research.seeburger.com/") 
public class IKeyRequestorService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://requestor.sharing.keymanagement.layers.securityframework.research.seeburger.com/", "IKeyRequestorService");
    public final static QName IKeyRequestorPort = new QName("http://requestor.sharing.keymanagement.layers.securityframework.research.seeburger.com/", "IKeyRequestorPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/IMSE/4.Thesis/Projects/ThesisProject/securityframework/../keyrequesteriface/src/main/resources/wsdl/KeyRequestorWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IKeyRequestorService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/IMSE/4.Thesis/Projects/ThesisProject/securityframework/../keyrequesteriface/src/main/resources/wsdl/KeyRequestorWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IKeyRequestorService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IKeyRequestorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IKeyRequestorService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IKeyRequestor
     */
    @WebEndpoint(name = "IKeyRequestorPort")
    public IKeyRequestor getIKeyRequestorPort() {
        return super.getPort(IKeyRequestorPort, IKeyRequestor.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IKeyRequestor
     */
    @WebEndpoint(name = "IKeyRequestorPort")
    public IKeyRequestor getIKeyRequestorPort(WebServiceFeature... features) {
        return super.getPort(IKeyRequestorPort, IKeyRequestor.class, features);
    }

}
