//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 11:08:27 PM CEST 
//


package com.seeburger.research.securityframework.configuration.types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for columnExceptionSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="columnExceptionSetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;choice>
 *           &lt;element name="specificColumnSetException" type="{http://securityframework.research.seeburger.com}columnSetExceptionType"/>
 *           &lt;element name="prefixedColumnSetException" type="{http://securityframework.research.seeburger.com}columnSetExceptionType"/>
 *           &lt;element name="regexFilteredColumnSetException" type="{http://securityframework.research.seeburger.com}columnSetExceptionType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "columnExceptionSetType", propOrder = {
    "specificColumnSetExceptionOrPrefixedColumnSetExceptionOrRegexFilteredColumnSetException"
})
public class ColumnExceptionSetType {

    @XmlElementRefs({
        @XmlElementRef(name = "prefixedColumnSetException", namespace = "http://securityframework.research.seeburger.com", type = JAXBElement.class),
        @XmlElementRef(name = "regexFilteredColumnSetException", namespace = "http://securityframework.research.seeburger.com", type = JAXBElement.class),
        @XmlElementRef(name = "specificColumnSetException", namespace = "http://securityframework.research.seeburger.com", type = JAXBElement.class)
    })
    protected List<JAXBElement<ColumnSetExceptionType>> specificColumnSetExceptionOrPrefixedColumnSetExceptionOrRegexFilteredColumnSetException;

    /**
     * Gets the value of the specificColumnSetExceptionOrPrefixedColumnSetExceptionOrRegexFilteredColumnSetException property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specificColumnSetExceptionOrPrefixedColumnSetExceptionOrRegexFilteredColumnSetException property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecificColumnSetExceptionOrPrefixedColumnSetExceptionOrRegexFilteredColumnSetException().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link ColumnSetExceptionType }{@code >}
     * {@link JAXBElement }{@code <}{@link ColumnSetExceptionType }{@code >}
     * {@link JAXBElement }{@code <}{@link ColumnSetExceptionType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<ColumnSetExceptionType>> getSpecificColumnSetExceptionOrPrefixedColumnSetExceptionOrRegexFilteredColumnSetException() {
        if (specificColumnSetExceptionOrPrefixedColumnSetExceptionOrRegexFilteredColumnSetException == null) {
            specificColumnSetExceptionOrPrefixedColumnSetExceptionOrRegexFilteredColumnSetException = new ArrayList<JAXBElement<ColumnSetExceptionType>>();
        }
        return this.specificColumnSetExceptionOrPrefixedColumnSetExceptionOrRegexFilteredColumnSetException;
    }

}
