//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 11:08:27 PM CEST 
//


package com.seeburger.research.securityframework.configuration.types;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for columnFamilyAsset complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="columnFamilyAsset">
 *   &lt;complexContent>
 *     &lt;extension base="{http://securityframework.research.seeburger.com}encryptedAsset">
 *       &lt;sequence>
 *         &lt;element name="columnExceptionSet" type="{http://securityframework.research.seeburger.com}columnExceptionSetType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="defaultEncryptionPolicy" type="{http://securityframework.research.seeburger.com}allOrNothingType" default="ALL" />
 *       &lt;attribute name="sharingGranularity" type="{http://securityframework.research.seeburger.com}granularityType" default="self" />
 *       &lt;attribute name="cacheSize" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *       &lt;attribute name="owner" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "columnFamilyAsset", propOrder = {
    "columnExceptionSet"
})
public class ColumnFamilyAsset
    extends EncryptedAsset
{

    protected ColumnExceptionSetType columnExceptionSet;
    @XmlAttribute
    protected AllOrNothingType defaultEncryptionPolicy;
    @XmlAttribute
    protected GranularityType sharingGranularity;
    @XmlAttribute
    protected Integer cacheSize;
    @XmlAttribute
    protected Boolean owner;

    /**
     * Gets the value of the columnExceptionSet property.
     * 
     * @return
     *     possible object is
     *     {@link ColumnExceptionSetType }
     *     
     */
    public ColumnExceptionSetType getColumnExceptionSet() {
        return columnExceptionSet;
    }

    /**
     * Sets the value of the columnExceptionSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColumnExceptionSetType }
     *     
     */
    public void setColumnExceptionSet(ColumnExceptionSetType value) {
        this.columnExceptionSet = value;
    }

    /**
     * Gets the value of the defaultEncryptionPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link AllOrNothingType }
     *     
     */
    public AllOrNothingType getDefaultEncryptionPolicy() {
        if (defaultEncryptionPolicy == null) {
            return AllOrNothingType.ALL;
        } else {
            return defaultEncryptionPolicy;
        }
    }

    /**
     * Sets the value of the defaultEncryptionPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllOrNothingType }
     *     
     */
    public void setDefaultEncryptionPolicy(AllOrNothingType value) {
        this.defaultEncryptionPolicy = value;
    }

    /**
     * Gets the value of the sharingGranularity property.
     * 
     * @return
     *     possible object is
     *     {@link GranularityType }
     *     
     */
    public GranularityType getSharingGranularity() {
        if (sharingGranularity == null) {
            return GranularityType.SELF;
        } else {
            return sharingGranularity;
        }
    }

    /**
     * Sets the value of the sharingGranularity property.
     * 
     * @param value
     *     allowed object is
     *     {@link GranularityType }
     *     
     */
    public void setSharingGranularity(GranularityType value) {
        this.sharingGranularity = value;
    }

    /**
     * Gets the value of the cacheSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getCacheSize() {
        if (cacheSize == null) {
            return  0;
        } else {
            return cacheSize;
        }
    }

    /**
     * Sets the value of the cacheSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCacheSize(Integer value) {
        this.cacheSize = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOwner(Boolean value) {
        this.owner = value;
    }

}
