//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 11:21:36 PM CEST 
//


package com.seeburger.research.securityframework.configuration.types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GeneratorKeys">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="location" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="keySharingEndpoint" type="{http://securityframework.research.seeburger.com}wsEndpoint" minOccurs="0"/>
 *         &lt;element name="Providers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Provider" type="{http://securityframework.research.seeburger.com}providerType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EncryptedAssets">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="keyspace" type="{http://securityframework.research.seeburger.com}keyspaceAsset" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "generatorKeys",
    "keySharingEndpoint",
    "providers",
    "encryptedAssets"
})
@XmlRootElement(name = "Config")
public class Config {

    @XmlElement(name = "GeneratorKeys", required = true)
    protected Config.GeneratorKeys generatorKeys;
    protected WsEndpoint keySharingEndpoint;
    @XmlElement(name = "Providers")
    protected Config.Providers providers;
    @XmlElement(name = "EncryptedAssets", required = true)
    protected Config.EncryptedAssets encryptedAssets;

    /**
     * Gets the value of the generatorKeys property.
     * 
     * @return
     *     possible object is
     *     {@link Config.GeneratorKeys }
     *     
     */
    public Config.GeneratorKeys getGeneratorKeys() {
        return generatorKeys;
    }

    /**
     * Sets the value of the generatorKeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link Config.GeneratorKeys }
     *     
     */
    public void setGeneratorKeys(Config.GeneratorKeys value) {
        this.generatorKeys = value;
    }

    /**
     * Gets the value of the keySharingEndpoint property.
     * 
     * @return
     *     possible object is
     *     {@link WsEndpoint }
     *     
     */
    public WsEndpoint getKeySharingEndpoint() {
        return keySharingEndpoint;
    }

    /**
     * Sets the value of the keySharingEndpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link WsEndpoint }
     *     
     */
    public void setKeySharingEndpoint(WsEndpoint value) {
        this.keySharingEndpoint = value;
    }

    /**
     * Gets the value of the providers property.
     * 
     * @return
     *     possible object is
     *     {@link Config.Providers }
     *     
     */
    public Config.Providers getProviders() {
        return providers;
    }

    /**
     * Sets the value of the providers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Config.Providers }
     *     
     */
    public void setProviders(Config.Providers value) {
        this.providers = value;
    }

    /**
     * Gets the value of the encryptedAssets property.
     * 
     * @return
     *     possible object is
     *     {@link Config.EncryptedAssets }
     *     
     */
    public Config.EncryptedAssets getEncryptedAssets() {
        return encryptedAssets;
    }

    /**
     * Sets the value of the encryptedAssets property.
     * 
     * @param value
     *     allowed object is
     *     {@link Config.EncryptedAssets }
     *     
     */
    public void setEncryptedAssets(Config.EncryptedAssets value) {
        this.encryptedAssets = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="keyspace" type="{http://securityframework.research.seeburger.com}keyspaceAsset" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "keyspace"
    })
    public static class EncryptedAssets {

        @XmlElement(required = true)
        protected List<KeyspaceAsset> keyspace;

        /**
         * Gets the value of the keyspace property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the keyspace property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getKeyspace().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link KeyspaceAsset }
         * 
         * 
         */
        public List<KeyspaceAsset> getKeyspace() {
            if (keyspace == null) {
                keyspace = new ArrayList<KeyspaceAsset>();
            }
            return this.keyspace;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="location" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class GeneratorKeys {

        @XmlAttribute(required = true)
        @XmlSchemaType(name = "anyURI")
        protected String location;

        /**
         * Gets the value of the location property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocation() {
            return location;
        }

        /**
         * Sets the value of the location property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocation(String value) {
            this.location = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Provider" type="{http://securityframework.research.seeburger.com}providerType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "provider"
    })
    public static class Providers {

        @XmlElement(name = "Provider", required = true)
        protected List<ProviderType> provider;

        /**
         * Gets the value of the provider property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the provider property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProvider().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProviderType }
         * 
         * 
         */
        public List<ProviderType> getProvider() {
            if (provider == null) {
                provider = new ArrayList<ProviderType>();
            }
            return this.provider;
        }

    }

}
