//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 11:08:27 PM CEST 
//


package com.seeburger.research.securityframework.configuration.types;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for keyspaceAsset complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="keyspaceAsset">
 *   &lt;complexContent>
 *     &lt;extension base="{http://securityframework.research.seeburger.com}encryptedAsset">
 *       &lt;sequence>
 *         &lt;element name="columnFamily" type="{http://securityframework.research.seeburger.com}columnFamilyAsset" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="owner" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "keyspaceAsset", propOrder = {
    "columnFamily"
})
public class KeyspaceAsset
    extends EncryptedAsset
{

    protected List<ColumnFamilyAsset> columnFamily;
    @XmlAttribute
    protected Boolean owner;

    /**
     * Gets the value of the columnFamily property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the columnFamily property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColumnFamily().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ColumnFamilyAsset }
     * 
     * 
     */
    public List<ColumnFamilyAsset> getColumnFamily() {
        if (columnFamily == null) {
            columnFamily = new ArrayList<ColumnFamilyAsset>();
        }
        return this.columnFamily;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOwner() {
        if (owner == null) {
            return true;
        } else {
            return owner;
        }
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOwner(Boolean value) {
        this.owner = value;
    }

}
