//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.15 at 11:08:27 PM CEST 
//


package com.seeburger.research.securityframework.configuration.types;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.seeburger.research.securityframework.configuration.types package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ColumnExceptionSetTypeRegexFilteredColumnSetException_QNAME = new QName("http://securityframework.research.seeburger.com", "regexFilteredColumnSetException");
    private final static QName _ColumnExceptionSetTypePrefixedColumnSetException_QNAME = new QName("http://securityframework.research.seeburger.com", "prefixedColumnSetException");
    private final static QName _ColumnExceptionSetTypeSpecificColumnSetException_QNAME = new QName("http://securityframework.research.seeburger.com", "specificColumnSetException");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.seeburger.research.securityframework.configuration.types
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ProviderType }
     * 
     */
    public ProviderType createProviderType() {
        return new ProviderType();
    }

    /**
     * Create an instance of {@link Config.GeneratorKeys }
     * 
     */
    public Config.GeneratorKeys createConfigGeneratorKeys() {
        return new Config.GeneratorKeys();
    }

    /**
     * Create an instance of {@link Config.Providers }
     * 
     */
    public Config.Providers createConfigProviders() {
        return new Config.Providers();
    }

    /**
     * Create an instance of {@link WsEndpoint }
     * 
     */
    public WsEndpoint createWsEndpoint() {
        return new WsEndpoint();
    }

    /**
     * Create an instance of {@link ColumnSetExceptionType }
     * 
     */
    public ColumnSetExceptionType createColumnSetExceptionType() {
        return new ColumnSetExceptionType();
    }

    /**
     * Create an instance of {@link Config.EncryptedAssets }
     * 
     */
    public Config.EncryptedAssets createConfigEncryptedAssets() {
        return new Config.EncryptedAssets();
    }

    /**
     * Create an instance of {@link Config }
     * 
     */
    public Config createConfig() {
        return new Config();
    }

    /**
     * Create an instance of {@link KeyspaceAsset }
     * 
     */
    public KeyspaceAsset createKeyspaceAsset() {
        return new KeyspaceAsset();
    }

    /**
     * Create an instance of {@link ColumnExceptionSetType }
     * 
     */
    public ColumnExceptionSetType createColumnExceptionSetType() {
        return new ColumnExceptionSetType();
    }

    /**
     * Create an instance of {@link ColumnFamilyAsset }
     * 
     */
    public ColumnFamilyAsset createColumnFamilyAsset() {
        return new ColumnFamilyAsset();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ColumnSetExceptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://securityframework.research.seeburger.com", name = "regexFilteredColumnSetException", scope = ColumnExceptionSetType.class)
    public JAXBElement<ColumnSetExceptionType> createColumnExceptionSetTypeRegexFilteredColumnSetException(ColumnSetExceptionType value) {
        return new JAXBElement<ColumnSetExceptionType>(_ColumnExceptionSetTypeRegexFilteredColumnSetException_QNAME, ColumnSetExceptionType.class, ColumnExceptionSetType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ColumnSetExceptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://securityframework.research.seeburger.com", name = "prefixedColumnSetException", scope = ColumnExceptionSetType.class)
    public JAXBElement<ColumnSetExceptionType> createColumnExceptionSetTypePrefixedColumnSetException(ColumnSetExceptionType value) {
        return new JAXBElement<ColumnSetExceptionType>(_ColumnExceptionSetTypePrefixedColumnSetException_QNAME, ColumnSetExceptionType.class, ColumnExceptionSetType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ColumnSetExceptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://securityframework.research.seeburger.com", name = "specificColumnSetException", scope = ColumnExceptionSetType.class)
    public JAXBElement<ColumnSetExceptionType> createColumnExceptionSetTypeSpecificColumnSetException(ColumnSetExceptionType value) {
        return new JAXBElement<ColumnSetExceptionType>(_ColumnExceptionSetTypeSpecificColumnSetException_QNAME, ColumnSetExceptionType.class, ColumnExceptionSetType.class, value);
    }

}
